### ISSUE TITLE
Construct architectural diagrams

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/sybvals#14]
Based on those (Fig 7 & 8) in the SyBLaRS paper, can we construct architectural diagrams for SyBValS as well? Let's please use drawio.

**Comment by hasanbalci** [comment]
About architecture diagram:
- There should be an access arrow from Sybvals to Cytoscape.js.
- Let's add the layout-utilities extension to the Cytoscape.js extensions box; fcose is using it.
- If I'm not mistaken, the things we call sbgnml-to-cytoscape and cytoscape-to-sbgnml are files we got from sbgnviz.js. Maybe we can write sbgnviz.js instead of them, even if we don't use it directly as a dependency.
- As far as I know, we also use libsbgn.js when using those files, so maybe we can structure it as sybvals -> sbgnviz.js -> libsbgn.js.
- xml2js and saxonjs can also be added to the Sybvals box, as we use them to process errors.

**Comment by hasanbalci** [comment]
The architecture diagram looks ok. About flow diagram:
- In client side, there is no SBGNML output (only errors and image)
- In server side, from Map box to Image Data, I considered something like this:
<img width="1095" alt="Screenshot 2024-07-11 at 20 11 47" src="https://github.com/user-attachments/assets/5b15443e-a226-4a53-af83-2320b55a0e80">
@YusufZiyaOzgul What do you think, is that correct? I considered that resolving errors is a conditional step after validation(error finding). Also even if we don't give error data directly to Cytosnap, we need to show it as input to Cytosnap because we give that information implicitly. Lastly, I couldn't connect Map box to No edge properly, maybe a better way can be considered.

**Comment by hasanbalci** [comment]
I reviewed the diagrams, final versions seem ok in terms of flow and logic.

**Comment by ugurdogrusoz** [comment]
I changed the style of Fig 8. @hasanbalci please check again in case I messed up something while formatting.

**Comment by ugurdogrusoz** [comment]
Fig 7 is ready for review as well. I also integrated both into the paper.

**Comment by hasanbalci** [comment]
They look good, thanks!
